# Generated by Django 3.2.3 on 2021-05-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
