# Generated by Django 3.2.3 on 2021-05-30 10:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210530_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
